/**
 * rs_eras.js — Rumble Slaughter Era System
 * Each era has: color, intro, fight, win, elim, chaos, humiliation, revive, autoRevive lines
 */

const ERAS = {

  // ── DEFAULT ────────────────────────────────────────────────────────────────
  default: {
    name: 'Rumble Slaughter: You Thought You Ate',
    color: '#d896ff',
    intro: null, // uses default lobby
  },

  // ── GUT FEELING ERA ────────────────────────────────────────────────────────
  'gut feeling era': {
    name: 'Gut Feeling Era',
    color: '#fc708e',
    intro: [
      'something in the air smells like blood and bad decisions. trust your gut. it\'s already wrong.',
      'the arena opened. your instincts said run. you stayed anyway.',
      'gut feeling era. visceral. raw. feral. you won\'t leave the same.',
      'your body knows what\'s coming. your brain is still pretending it\'s fine.',
    ],
    fight: [
      '@attacker felt it before it happened. @target didn\'t.',
      '@attacker moved on instinct. @target moved on ego. only one survived.',
      '@attacker said something\'s wrong and it was @target.',
      '@attacker didn\'t think. just acted. @target is gone.',
      '@attacker smelled the weakness on @target and moved accordingly.',
      '@attacker trusted the gut. the gut said destroy @target.',
      '@attacker made a primal decision about @target. correct decision.',
      '@target should have listened to their body. it was screaming leave.',
      '@attacker went feral on @target and nobody is shocked.',
      '@attacker felt a pull toward @target. the pull was violent.',
      '@attacker said something feels off about @target. eliminated.',
      '@target stood still when they should have run. @attacker noticed.',
      '@attacker acted before @target even processed what was happening.',
      '@attacker didn\'t blink. @target did. that was enough.',
    ],
    win: [
      '@winner survived on instinct alone. their brain was barely involved.',
      '@winner felt victory before it happened. the arena just confirmed it.',
      '@winner moved like something raw and feral and untouchable.',
      '@winner\'s gut said win. their gut has never been wrong.',
      '@winner didn\'t strategize. they just knew. terrifying.',
      '@winner survived because something inside them refused to stop.',
      '@winner is built from something primal. the arena felt it.',
      '@winner wins. raw. unhinged. inevitable.',
      '@winner said I can feel it and they were absolutely right.',
    ],
    elim: [
      '@user ignored every warning sign and walked straight into elimination.',
      '@user\'s instincts said danger. @user said I\'ll be fine.',
      '@user felt something was wrong and proceeded anyway. classic.',
      '@user had a bad feeling. they were right. they\'re gone.',
      '@user\'s body tried to save them. their confidence overruled it.',
      '@user should have trusted the pit in their stomach.',
      '@user walked in already knowing the outcome. this is that outcome.',
      '@user got eliminated and honestly their gut told them this would happen.',
      '@user ignored every signal. the arena made the decision for them.',
    ],
    chaos: [
      { text: 'the arena\'s stomach dropped. someone was removed.',                          type: 'random_elim', count: 1 },
      { text: 'something shifted. the blood ran cold. players disappeared.',                  type: 'mass_elim',   count: 2 },
      { text: 'gut feeling era activated. the arena acted on instinct.',                      type: 'random_elim', count: 2 },
      { text: 'the primal energy peaked. someone paid for it.',                               type: 'random_elim', count: 1 },
      { text: 'the arena felt something feral. multiple eliminations.',                       type: 'mass_elim',   count: 3 },
      { text: 'raw instinct took over. the arena chose violence.',                            type: 'random_elim', count: 1 },
    ],
    humiliation: [
      '@user got eliminated and their gut had warned them three rounds ago.',
      '@user trusted the wrong instinct. specifically the one that said stay.',
      '@user\'s primal brain said fight. their skill level said don\'t.',
      '@user lost in a way that felt biological. like a natural predator rejected them.',
      '@user got eliminated with the energy of prey that forgot it was prey.',
    ],
    revive: [
      '@user refused to die. something feral brought them back.',
      'the arena\'s gut said @user isn\'t done. @user is back.',
      '@user got up on pure instinct. terrifying.',
      '@user crawled back with the energy of something that doesn\'t know how to stay dead.',
    ],
    autoRevive: [
      '🩸 the arena felt @user wasn\'t finished. they\'re back. trust the gut.',
      '🩸 something raw pulled @user back. they\'re alive again. nobody planned this.',
      '🩸 gut feeling said @user survives. @user survives.',
    ],
  },

  // ── DARLING I BITE ─────────────────────────────────────────────────────────
  'darling i bite': {
    name: 'Darling I Bite',
    color: '#fe019a',
    intro: [
      'darling i bite era. come close. that\'s how this works.',
      'the arena is dressed for dinner and you\'re the course.',
      'predatory. velvet. lethal. welcome to the last place you should have come.',
      'the lights are low. everyone smells like something about to end.',
    ],
    fight: [
      '@attacker smiled at @target first. then eliminated them. in that order.',
      '@attacker said you look lovely right before ending @target.',
      '@attacker leaned in close to @target. that was the last thing @target felt.',
      '@attacker eliminated @target tenderly. somehow that made it worse.',
      '@attacker said darling and then did something unforgivable to @target.',
      '@attacker looked @target in the eyes. @target won\'t recover from that.',
      '@attacker was sweet about it. @target is still eliminated.',
      '@attacker said this won\'t hurt and eliminated @target.',
      '@attacker killed @target with the gentleness of someone who\'s done this before.',
      '@attacker made @target feel chosen. then eliminated them. correctly.',
      '@target got close to @attacker. that was the mistake.',
      '@attacker was the most dangerous thing @target ever trusted.',
      '@attacker moved slowly and deliberately toward @target. only one left.',
      '@attacker smiled. @target felt it. then felt nothing.',
    ],
    win: [
      '@winner wore the arena down like they had all night.',
      '@winner is the kind of dangerous that looks like a compliment.',
      '@winner wins. velvet and lethal and completely unbothered.',
      '@winner eliminated everyone with the patience of something predatory.',
      '@winner wins. darling.',
      '@winner is your champion. they dressed for this.',
      '@winner smiled through every elimination. that says everything.',
      '@winner wins. the arena wanted to lose to them anyway.',
    ],
    elim: [
      '@user trusted something beautiful. they\'re eliminated.',
      '@user got close to the wrong person and paid for it.',
      '@user thought they were the predator in this scenario. incorrect.',
      '@user fell for the oldest trick and the arena doesn\'t feel bad.',
      '@user got eliminated by something they probably still like.',
      '@user got bitten. they didn\'t listen to the name of the era.',
      '@user got eliminated with grace. which somehow made it worse.',
      '@user got handled like someone who knew exactly what they were doing. they didn\'t.',
    ],
    chaos: [
      { text: 'the arena said darling and eliminated someone.',                               type: 'random_elim', count: 1 },
      { text: 'the velvet gloves came off. multiple casualties.',                             type: 'mass_elim',   count: 2 },
      { text: 'darling I bite era reactivated. someone learned the hard way.',                type: 'random_elim', count: 1 },
      { text: 'the predatory energy spiked. the arena acted.',                                type: 'random_elim', count: 2 },
      { text: 'something seductive and fatal just happened. several are gone.',               type: 'mass_elim',   count: 3 },
    ],
    humiliation: [
      '@user got eliminated by something they probably found attractive. humiliating.',
      '@user didn\'t realize they were the prey until they were already eliminated.',
      '@user walked in thinking they were the most dangerous thing here. adorable.',
      '@user got handled so gently that the embarrassment outlasted the pain.',
      '@user thought darling was a term of endearment in this context. it wasn\'t.',
    ],
    revive: [
      '@user came back. something about them refused to stay down. darling.',
      'the arena didn\'t finish @user off properly. they\'re back.',
      '@user rose like something dramatic and predatory. they\'re not done.',
      '@user got up and the arena genuinely did not expect that.',
    ],
    autoRevive: [
      '💋 the arena decided @user wasn\'t done being dangerous. they\'re back.',
      '💋 @user got a second life. spend it wisely. or don\'t.',
      '💋 the arena said not yet to @user\'s elimination. terrifying.',
    ],
  },

  // ── BADDIE BODY COUNT ──────────────────────────────────────────────────────
  'baddie body count': {
    name: 'Baddie Body Count',
    color: '#00b8ff',
    intro: [
      'baddie body count era. the count is going up. so is the confidence.',
      'neon. glam. dominant. the arena just became the most dangerous runway.',
      'body count era activated. not the fun kind.',
      'the baddies have arrived. the body count is about to reflect that.',
    ],
    fight: [
      '@attacker added @target to the count. no hesitation.',
      '@attacker looked stunning eliminating @target.',
      '@attacker said body count goes up and @target became a statistic.',
      '@attacker eliminated @target without smudging their lip gloss.',
      '@attacker is collecting eliminations like accessories. @target is the latest.',
      '@attacker said another one and @target became another one.',
      '@attacker moved on @target with the confidence of someone who\'s done this before.',
      '@target got eliminated by someone who barely remembered their name.',
      '@attacker added @target to their personal record. still not impressed.',
      '@attacker got @target. the count updated.',
      '@attacker eliminated @target like it was a personality trait.',
      '@target thought they had a chance. @attacker knew otherwise.',
      '@attacker said count it and the count was counted.',
      '@target got dropped so fast the arena had to replay it.',
    ],
    win: [
      '@winner wins. the body count is respectable. the attitude more so.',
      '@winner cleared the arena and looks good doing it.',
      '@winner is your champion. the most dangerous baddie in the room.',
      '@winner added everyone to the count. that\'s the game.',
      '@winner wins. neon. dominant. correct.',
      '@winner finished the era with the highest count. as expected.',
      '@winner wins. confidence fully justified. unfortunately for everyone else.',
      '@winner said body count goes up and they made sure it did.',
    ],
    elim: [
      '@user got added to someone\'s count. didn\'t even make top 5.',
      '@user became a statistic in someone else\'s story.',
      '@user got eliminated by a baddie who won\'t remember this tomorrow.',
      '@user got dropped and the arena moved on immediately.',
      '@user is a body. the count has been updated.',
      '@user thought they were a main character. they were a number.',
      '@user got eliminated with the energy of someone checking a box.',
      '@user got added to the count and honestly it elevated the total.',
    ],
    chaos: [
      { text: 'baddie energy spiked. the count went up.',                                     type: 'random_elim', count: 1 },
      { text: 'the arena said body count and multiple people qualified.',                     type: 'mass_elim',   count: 2 },
      { text: 'neon lights flickered. chaos eliminated players.',                             type: 'random_elim', count: 2 },
      { text: 'the dominant energy activated. the arena cleared house.',                      type: 'mass_elim',   count: 3 },
      { text: 'glam chaos event. someone got dropped without warning.',                       type: 'random_elim', count: 1 },
    ],
    humiliation: [
      '@user got eliminated and didn\'t even make it into the notable casualties.',
      '@user got dropped by a baddie who was on the phone during the duel.',
      '@user thought they were giving baddie. they were giving background character.',
      '@user got eliminated so fast they didn\'t even get a close-up.',
      '@user became a number. the number is not impressive.',
    ],
    revive: [
      '@user said not today and came back. the count paused briefly.',
      'the baddie energy pulled @user back. they\'re not done.',
      '@user refused to be a body. back in the count as a contender.',
      '@user got back up and the arena had to respect the audacity.',
    ],
    autoRevive: [
      '💜 the arena gave @user another shot at the count. they\'re back.',
      '💜 @user won the revival lottery. use the second life better.',
      '💜 body count paused. @user is back in the arena.',
    ],
  },

  // ── KISS THEN KILL ─────────────────────────────────────────────────────────
  'kiss then kill': {
    name: 'Kiss Then Kill',
    color: '#FF6B9A',
    intro: [
      'kiss then kill era. in that order. don\'t mix it up.',
      'the arena is romantic tonight. that\'s the most dangerous thing it could be.',
      'you\'ll feel something before the end. it won\'t be what you expected.',
      'deceptive. glossy. venomous. the arena is dressed in rose pink and poison.',
    ],
    fight: [
      '@attacker said something kind to @target first. then eliminated them.',
      '@attacker made @target feel safe. that was the strategy.',
      '@attacker eliminated @target with the warmth of something truly deceptive.',
      '@target felt something sweet just before @attacker ended it.',
      '@attacker was nice about it. @target is still eliminated.',
      '@attacker poisoned the situation and @target didn\'t notice until it was over.',
      '@attacker gave @target hope. then took everything else.',
      '@attacker said you\'re doing great right before @target wasn\'t.',
      '@target trusted the softness. @attacker sharpened it.',
      '@attacker smiled through the entire elimination. @target did not.',
      '@attacker eliminated @target like they were doing them a favor.',
      '@target felt chosen. @attacker chose correctly. for @attacker.',
      '@attacker delivered something sweet and something lethal in the same motion.',
      '@attacker said I like you and then immediately proved that irrelevant.',
    ],
    win: [
      '@winner survived by being both the kindest and most dangerous thing here.',
      '@winner wins. poison pink. fully lethal. somehow still charming.',
      '@winner kissed the arena goodnight and won.',
      '@winner wins. the most deceptive victory this arena has seen.',
      '@winner eliminated everyone sweetly. that\'s a skill.',
      '@winner is champion. rose pink on the outside. poison on the inside.',
      '@winner wins. charming to the very last second.',
      '@winner said I care about all of you and eliminated all of you.',
    ],
    elim: [
      '@user got eliminated by something they trusted. that\'s the era.',
      '@user felt something warm right before the end. that was the trap.',
      '@user got taken out gently. that\'s almost worse.',
      '@user was the kiss. not the kill. eliminated.',
      '@user trusted the vibe. the vibe was lying.',
      '@user got eliminated and still doesn\'t know how it happened.',
      '@user fell for something glossy. the inside was poison.',
      '@user got eliminated tenderly. somehow more humiliating.',
    ],
    chaos: [
      { text: 'the arena kissed someone goodbye. they didn\'t come back.',                   type: 'random_elim', count: 1 },
      { text: 'something sweet turned lethal. multiple eliminations.',                        type: 'mass_elim',   count: 2 },
      { text: 'kiss then kill era delivered on the kill part. immediately.',                  type: 'random_elim', count: 1 },
      { text: 'the venomous energy activated. several players eliminated.',                   type: 'mass_elim',   count: 2 },
      { text: 'the arena said this is for your own good and eliminated someone.',             type: 'random_elim', count: 1 },
    ],
    humiliation: [
      '@user got eliminated by something that smiled at them first.',
      '@user thought they were safe because it felt nice. it didn\'t last.',
      '@user got done in by the softness. that\'s the most embarrassing kind.',
      '@user got eliminated and the arena still feels fond of them. doesn\'t help.',
      '@user trusted warmth in an arena named kiss then kill. lesson learned.',
    ],
    revive: [
      '@user came back. the kiss wasn\'t the end after all.',
      '@user survived the kill part. somehow. they\'re back.',
      'the arena breathed life back into @user. suspiciously warm of it.',
      '@user got another chance. don\'t trust whatever gave it to them.',
    ],
    autoRevive: [
      '🌹 the arena kissed @user back to life. they\'re back. be careful.',
      '🌹 @user got revived. sweetly. suspiciously.',
      '🌹 the kiss won. the kill is postponed. @user is alive.',
    ],
  },

  // ── EAT OR BE EATEN ────────────────────────────────────────────────────────
  'eat or be eaten': {
    name: 'Eat or Be Eaten',
    color: '#fefacc',
    intro: [
      'eat or be eaten era. the arena doesn\'t do nuance tonight.',
      'primal. feral. survival only. no room for anything else.',
      'the rules are simple. eat first.',
      'burnt orange and ash black. everyone is food or hungry. pick one.',
    ],
    fight: [
      '@attacker ate @target. no further explanation.',
      '@attacker was hungry. @target was available.',
      '@attacker chose eat. @target became the meal.',
      '@target hesitated. @attacker didn\'t. the natural order reasserted itself.',
      '@attacker said eat or be eaten and chose eat. immediately.',
      '@target was the weaker predator. @attacker solved that.',
      '@attacker got to @target before @target got to anyone.',
      '@attacker identified @target as prey and acted on it.',
      '@target was outpredated by @attacker in real time.',
      '@attacker consumed @target\'s entire vibe and left.',
      '@attacker didn\'t come here to be eaten. @target came here to be eliminated.',
      '@target stopped moving for a second. @attacker was already moving.',
      '@attacker said the food chain is real and demonstrated on @target.',
      '@target showed vulnerability. @attacker is feral. outcome expected.',
    ],
    win: [
      '@winner ate everyone and is still hungry. the arena is concerned.',
      '@winner is the apex predator of this arena. undisputed.',
      '@winner chose eat every time. the count proves it.',
      '@winner wins. primal. dominant. still looking for more.',
      '@winner survived by being the most dangerous thing here. always was.',
      '@winner is your champion. the food chain resolved itself.',
      '@winner ate or be eaten and consistently chose the first option.',
      '@winner wins. feral. correct. victorious.',
    ],
    elim: [
      '@user got eaten. that\'s the era.',
      '@user was the be eaten part of the equation.',
      '@user came in hungry and left as someone else\'s meal.',
      '@user got consumed by the arena before they could consume anyone.',
      '@user was prey today. no shame. just facts.',
      '@user got outpredated before they could establish dominance.',
      '@user thought they were the predator. the arena clarified.',
      '@user became food. the elimination was prompt.',
    ],
    chaos: [
      { text: 'the food chain collapsed. someone got eaten by the arena itself.',             type: 'random_elim', count: 1 },
      { text: 'the primal energy peaked. multiple players consumed.',                         type: 'mass_elim',   count: 2 },
      { text: 'eat or be eaten activated literally. several casualties.',                     type: 'mass_elim',   count: 3 },
      { text: 'something feral moved through the arena. someone paid.',                       type: 'random_elim', count: 1 },
      { text: 'the arena got hungry. eliminated someone.',                                    type: 'random_elim', count: 2 },
    ],
    humiliation: [
      '@user got eaten and didn\'t even put up a fight. embarrassing for the predator.',
      '@user was the easiest meal in the arena. the elimination was fast.',
      '@user got consumed so quickly the arena barely registered it.',
      '@user was hunted. found. eliminated. in that sequence. quickly.',
      '@user thought \'eat or be eaten\' was a metaphor. it wasn\'t.',
    ],
    revive: [
      '@user refused to be digested. they\'re back.',
      'the arena spat @user back out. they\'re alive again.',
      '@user clawed their way back from being eliminated. feral energy.',
      '@user said I\'m not food and proved it by surviving.',
    ],
    autoRevive: [
      '🦴 the arena decided @user wasn\'t done hunting. they\'re back.',
      '🦴 @user got another life. eat faster this time.',
      '🦴 the primal force revived @user. the hunt continues.',
    ],
  },

  // ── BLOOD BUFFET ───────────────────────────────────────────────────────────
  'blood buffet': {
    name: 'Blood Buffet',
    color: '#e20000',
    intro: [
      'blood buffet era. everyone\'s on the menu. help yourself.',
      'the arena laid out a spread. you\'re all invited. none of you are guests.',
      'gluttonous. chaotic. excessive. the buffet is open.',
      'deep red and slime green. come hungry. leave eliminated. or don\'t leave.',
    ],
    fight: [
      '@attacker helped themselves to @target. the buffet is serving.',
      '@attacker got a full plate out of @target.',
      '@attacker said what\'s on the menu and found @target.',
      '@attacker is having a great evening. @target is not.',
      '@attacker took @target off the board and went back for seconds.',
      '@attacker said I\'ll have @target and the arena obliged.',
      '@target was the first course. @attacker is still hungry.',
      '@attacker moved through @target like they were starving.',
      '@attacker said the buffet is open and started with @target.',
      '@target got served. @attacker is the chef.',
      '@attacker eliminated @target like a starter. efficient. thorough.',
      '@attacker consumed @target\'s entire existence in one round.',
      '@target walked into the buffet not realizing they were the entrée.',
      '@attacker helped themselves aggressively to @target.',
    ],
    win: [
      '@winner ate the whole buffet. everyone.',
      '@winner had a full course meal tonight. everyone else was on the menu.',
      '@winner wins. gluttonous. victorious. still not satisfied.',
      '@winner cleared every plate. the arena is impressed and unsettled.',
      '@winner said I\'ll have everyone and meant it.',
      '@winner wins. the most excessive victory available.',
      '@winner finished the buffet alone. as intended.',
      '@winner is champion. the spread has been cleared. the carnage appreciated.',
    ],
    elim: [
      '@user got served. didn\'t see it coming.',
      '@user was on the menu and didn\'t know it.',
      '@user got plated and eliminated.',
      '@user became someone else\'s course. a small one.',
      '@user showed up to the buffet as food. eliminated accordingly.',
      '@user got consumed and the arena asked for more.',
      '@user was an appetizer. the buffet barely noticed.',
      '@user got eliminated with the efficiency of someone who came hungry.',
    ],
    chaos: [
      { text: 'the buffet expanded. someone unexpected was served.',                          type: 'random_elim', count: 1 },
      { text: 'blood buffet era hit the chaotic phase. multiple served.',                     type: 'mass_elim',   count: 2 },
      { text: 'the menu updated without notice. several eliminated.',                         type: 'mass_elim',   count: 3 },
      { text: 'the arena added a surprise course. one player eliminated.',                    type: 'random_elim', count: 1 },
      { text: 'the buffet got excessive. chaos spread. casualties mounted.',                  type: 'random_elim', count: 2 },
    ],
    humiliation: [
      '@user got plated so fast the arena didn\'t even warm the dish.',
      '@user was eliminated like a side dish. not even the feature.',
      '@user got consumed and didn\'t even flavor the experience.',
      '@user showed up to the blood buffet and got immediately served.',
      '@user was the cheapest thing on the menu. eliminated first.',
    ],
    revive: [
      '@user crawled back from the buffet. not done being served.',
      '@user refused to stay on the plate. they\'re back.',
      'the arena reconsidered @user\'s elimination. they\'re alive.',
      '@user got up from the table. uninvited. unstoppable.',
    ],
    autoRevive: [
      '🩸 the buffet spat @user back out. they\'re alive again.',
      '🩸 @user got a second serving of life. use it.',
      '🩸 the arena reconsidered @user as a casualty. back in the game.',
    ],
  },

  // ── SERVED YOU WRONG ───────────────────────────────────────────────────────
  'served you wrong': {
    name: 'Served You Wrong',
    color: '#ffffff',
    intro: [
      'served you wrong era. the arena has a list. you\'re on it.',
      'acid purple. electric blue. and a very specific grudge.',
      'spiteful. sharp. petty. the arena remembered everything.',
      'this isn\'t random. this is intentional. served.',
    ],
    fight: [
      '@attacker had something to settle with @target. settled.',
      '@attacker remembered what @target did. @target is eliminated.',
      '@attacker said this one\'s personal and pointed at @target.',
      '@attacker served @target wrong on purpose. correct.',
      '@attacker eliminated @target with the energy of someone who has been waiting.',
      '@attacker didn\'t forget. @target should have apologized.',
      '@attacker said you owe me and collected from @target.',
      '@target did something @attacker didn\'t appreciate. the bill came due.',
      '@attacker eliminated @target and said that\'s for everything.',
      '@attacker chose @target specifically. this was not random.',
      '@attacker handled @target with the precision of someone who planned this.',
      '@target thought it was water under the bridge. @attacker kept receipts.',
      '@attacker said your table is ready and served @target immediately.',
      '@attacker got @target with the satisfaction of someone long overdue.',
    ],
    win: [
      '@winner wins. the receipts were valid. the revenge was served.',
      '@winner settled every account in this arena. champion.',
      '@winner wins. spiteful. correct. satisfied.',
      '@winner said I remembered and proved it comprehensively.',
      '@winner wins. the list has been completed.',
      '@winner served everyone wrong and did it on purpose.',
      '@winner is champion. the acid purple said so.',
      '@winner wins. petty and correct. the best combination.',
    ],
    elim: [
      '@user got served exactly what they deserved.',
      '@user had this coming. the arena kept track.',
      '@user got eliminated with a receipt attached.',
      '@user was on someone\'s list. crossed off.',
      '@user got what was owed. elimination is the currency.',
      '@user thought they were forgotten. they weren\'t.',
      '@user got served wrong on purpose. nothing accidental about this.',
      '@user is eliminated. the arena said you know what you did.',
    ],
    chaos: [
      { text: 'the arena settled a score. someone eliminated.',                               type: 'random_elim', count: 1 },
      { text: 'served you wrong era delivered on multiple debts.',                            type: 'mass_elim',   count: 2 },
      { text: 'the receipts came out. several players eliminated.',                           type: 'random_elim', count: 2 },
      { text: 'the arena remembered something. chaos ensued.',                                type: 'mass_elim',   count: 3 },
      { text: 'the grudge peaked. someone paid for it.',                                      type: 'random_elim', count: 1 },
    ],
    humiliation: [
      '@user got eliminated and it was personal. the arena specified.',
      '@user got served wrong with intention and precision.',
      '@user had this coming from round one. the arena waited.',
      '@user got eliminated by something that took its time getting to them.',
      '@user got receipted out of the arena. humiliating.',
    ],
    revive: [
      '@user got back up. the score isn\'t settled yet.',
      '@user came back to finish what they started.',
      'the arena gave @user another chance to settle things.',
      '@user returned. there are still debts outstanding.',
    ],
    autoRevive: [
      '⚡ the arena said @user has unfinished business. they\'re back.',
      '⚡ @user got revived specifically to serve someone else wrong.',
      '⚡ the grudge continues. @user is alive again.',
    ],
  },

  // ── NO SURVIVORS ERA ───────────────────────────────────────────────────────
  'no survivors era': {
    name: 'No Survivors Era',
    color: '#000000',
    intro: [
      'no survivors era. the name is accurate. enter accordingly.',
      'matte black. steel gray. blood accent. the arena means this literally.',
      'cold. void. merciless. no one leaves this the same. most don\'t leave.',
      'no survivors era activated. this is your only warning.',
    ],
    fight: [
      '@attacker left no survivors starting with @target.',
      '@attacker processed @target with the efficiency of someone following a policy.',
      '@attacker said no survivors and @target was the first data point.',
      '@attacker eliminated @target coldly. without comment.',
      '@attacker moved through @target like a system running a process.',
      '@target was part of @attacker\'s no survivors policy. policy enforced.',
      '@attacker didn\'t speak. just eliminated @target. that\'s the era.',
      '@target tried to survive. @attacker\'s policy had other plans.',
      '@attacker removed @target from the survivor list. the list has no one left.',
      '@attacker eliminated @target without visible emotion. more unsettling.',
      '@attacker said nothing before or after @target\'s elimination. correct.',
      '@target found out what no survivors means in real time.',
      '@attacker closed the gap on @target with zero hesitation.',
      '@attacker and @target met. only @attacker continued.',
    ],
    win: [
      '@winner wins. no survivors. as advertised.',
      '@winner is the only survivor. the era kept its promise.',
      '@winner wins. cold. correct. merciless. undefeated.',
      '@winner left no survivors. the arena is empty. @winner remains.',
      '@winner wins. the void chose one.',
      '@winner is champion of an era that promised no survivors. ironic.',
      '@winner wins. steel gray and blood accent. everyone else: void.',
      '@winner said no survivors and made good on it.',
    ],
    elim: [
      '@user did not survive. the era was clear about this.',
      '@user became part of the no survivors statistic.',
      '@user is a casualty of an era that warned everyone.',
      '@user couldn\'t survive the era that named itself after this outcome.',
      '@user got eliminated. the era takes no joy in this. it just takes.',
      '@user is gone. the void is indifferent.',
      '@user tried. the era doesn\'t negotiate.',
      '@user got eliminated with the cold efficiency of something merciless.',
    ],
    chaos: [
      { text: 'no survivors era enforced its name. someone eliminated.',                     type: 'random_elim', count: 1 },
      { text: 'the void took multiple players. no explanation.',                              type: 'mass_elim',   count: 2 },
      { text: 'cold chaos event. several casualties. no survivors policy applied.',           type: 'mass_elim',   count: 3 },
      { text: 'the arena said no survivors and meant several right now.',                     type: 'random_elim', count: 2 },
      { text: 'the steel gray activated. the arena was merciless.',                           type: 'random_elim', count: 1 },
    ],
    humiliation: [
      '@user tried to be a survivor in an era called no survivors. optimistic.',
      '@user got eliminated with the clinical efficiency of something that doesn\'t care.',
      '@user became a data point in an era that processes everyone.',
      '@user got deleted by something that made no note of their passing.',
      '@user couldn\'t beat an era that made its intentions public.',
    ],
    revive: [
      '@user exists again. the no survivors policy has a glitch.',
      'the void spat @user back. unclear why.',
      '@user got a second life in an era that promised otherwise.',
      '@user returned. the no survivors count is temporarily wrong.',
    ],
    autoRevive: [
      '⚫ the void reconsidered @user. they\'re back. anomaly.',
      '⚫ @user got revived. the no survivors policy has an exception.',
      '⚫ the arena\'s merciless algorithm glitched. @user is alive.',
    ],
  },

  // ── YOU THOUGHT WRONG ──────────────────────────────────────────────────────
  'you thought wrong': {
    name: 'You Thought Wrong',
    color: '#f5a67c',
    intro: [
      'you thought wrong era. every assumption you walked in with is incorrect.',
      'neon yellow. glitch purple. chaotic. delusional. correct.',
      'the arena is unstable tonight. so is every plan you made.',
      'you thought wrong era. the arena is personally offended by your confidence.',
    ],
    fight: [
      '@attacker said you thought that would work and proved @target wrong.',
      '@target thought they had @attacker. @target thought wrong.',
      '@attacker watched @target\'s strategy fail in real time.',
      '@attacker said incorrect and eliminated @target.',
      '@target had a plan. @attacker had a better one. you thought wrong.',
      '@attacker said let me correct that and eliminated @target.',
      '@target was confident going in. @attacker adjusted that.',
      '@attacker eliminated @target mid-assumption.',
      '@target thought @attacker wasn\'t a threat. that was the wrong thought.',
      '@attacker corrected @target\'s miscalculation permanently.',
      '@target overestimated everything. @attacker underestimated nothing.',
      '@attacker said you thought wrong out loud and then proved it.',
      '@target built a strategy on a false premise. @attacker exploited it.',
      '@attacker eliminated @target and didn\'t even look surprised.',
    ],
    win: [
      '@winner wins. everyone thought wrong. @winner thought correctly.',
      '@winner is champion. the only one whose assumptions were valid.',
      '@winner said you\'ll all think wrong and was not incorrect.',
      '@winner wins. chaotic and right. a rare combination.',
      '@winner corrected every wrong thought in this arena. champion.',
      '@winner wins. neon yellow. glitch purple. completely right.',
      '@winner is the one who thought correctly. congratulations. unfortunately.',
      '@winner wins. everyone else was wrong. @winner knew it.',
    ],
    elim: [
      '@user thought they had a shot. incorrect.',
      '@user was wrong about every variable in this arena.',
      '@user\'s strategy was based on assumptions that were all wrong.',
      '@user thought this round was theirs. you thought wrong.',
      '@user miscalculated something fundamental and the arena corrected it.',
      '@user overestimated themselves by a significant margin.',
      '@user thought confidence was a substitute for accuracy. it wasn\'t.',
      '@user got eliminated for thinking incorrectly in real time.',
    ],
    chaos: [
      { text: 'the arena corrected multiple wrong assumptions simultaneously.',               type: 'mass_elim',   count: 2 },
      { text: 'you thought wrong era glitched. someone got eliminated.',                     type: 'random_elim', count: 1 },
      { text: 'neon chaos event. everyone\'s plan was wrong. casualties.',                   type: 'mass_elim',   count: 3 },
      { text: 'the arena said that\'s incorrect and removed someone.',                       type: 'random_elim', count: 1 },
      { text: 'wrong assumption activated chaos. multiple eliminations.',                    type: 'random_elim', count: 2 },
    ],
    humiliation: [
      '@user got eliminated for confidently thinking the wrong thing.',
      '@user\'s entire strategy was incorrect from the start. the arena waited to confirm.',
      '@user thought they understood the arena. they didn\'t. eliminated.',
      '@user got corrected so thoroughly the arena felt educational.',
      '@user was wrong in a way that required public elimination to address.',
    ],
    revive: [
      '@user got another shot. try thinking correctly this time.',
      '@user came back. the assumption this time better be right.',
      'the arena gave @user a correction. they\'re back.',
      '@user gets to try again. the wrong thoughts have been cleared.',
    ],
    autoRevive: [
      '💛 the arena said @user thought wrong but here\'s another chance.',
      '💛 @user revived. different thought required.',
      '💛 the glitch brought @user back. think correctly this time.',
    ],
  },

  // ── DELULU DESTROYER ───────────────────────────────────────────────────────
  'delulu destroyer': {
    name: 'Delulu Destroyer',
    color: '#00fff9',
    intro: [
      'delulu destroyer era. the most unhinged night this arena has ever hosted.',
      'electric green. neon magenta. static black. nothing makes sense. perfect.',
      'the arena is manic tonight. the eliminations will reflect that.',
      'delulu destroyer activated. the logic has left the building.',
    ],
    fight: [
      '@attacker was unhinged going into the fight with @target. it worked.',
      '@attacker eliminated @target through pure erratic energy.',
      '@target tried to predict @attacker. @attacker is unpredictable. eliminated.',
      '@attacker said something unhinged mid-fight and @target didn\'t recover.',
      '@attacker moved like someone who has never heard of strategy. @target is gone.',
      '@attacker was running on delusion and it carried them through @target.',
      '@target applied logic to an illogical opponent. that was the mistake.',
      '@attacker eliminated @target in a way nobody will be able to explain.',
      '@attacker said this is fine while eliminating @target. terrifying.',
      '@target expected a rational fight. @attacker didn\'t know what rational meant.',
      '@attacker manifested @target\'s elimination and then executed it.',
      '@attacker moved wrong but got the right result. @target is gone.',
      '@target had @attacker figured out until @attacker did something unhinged.',
      '@attacker said trust the delusion and @target became evidence it was right.',
    ],
    win: [
      '@winner wins. completely unhinged. completely victorious.',
      '@winner manifested this win so hard the arena had no choice.',
      '@winner wins. electric green. neon magenta. zero logic. all results.',
      '@winner destroyed the arena on pure delusion. champion.',
      '@winner wins. the most erratic victory this arena has documented.',
      '@winner said I\'m going to win and kept saying it until it was true.',
      '@winner is champion. the delusion was correct the whole time.',
      '@winner wins. manic energy. maximum results.',
    ],
    elim: [
      '@user tried to fight someone running on pure delusion. incorrect approach.',
      '@user got eliminated by chaos that made no logical sense.',
      '@user was rational in an irrational era. that was the problem.',
      '@user got destroyed by something they couldn\'t predict because it couldn\'t predict itself.',
      '@user got eliminated by vibes alone. specifically unhinged vibes.',
      '@user was in the wrong headspace for this era.',
      '@user applied common sense to a delulu destroyer match. eliminated.',
      '@user got erratically eliminated and the arena can\'t fully explain it.',
    ],
    chaos: [
      { text: 'delulu energy peaked. the arena went unhinged. casualty.',                    type: 'random_elim', count: 1 },
      { text: 'manic chaos event. multiple eliminations. no explanation.',                   type: 'mass_elim',   count: 2 },
      { text: 'the static activated. the arena got erratic. several gone.',                  type: 'mass_elim',   count: 3 },
      { text: 'the arena said this is fine and eliminated someone.',                         type: 'random_elim', count: 1 },
      { text: 'electric green chaos event. two players eliminated randomly.',                type: 'random_elim', count: 2 },
    ],
    humiliation: [
      '@user got eliminated in a way that defied logic. they were on the wrong side of it.',
      '@user tried to be stable in an unstable era. the arena punished that.',
      '@user got destroyed by pure delusion and the worst part is it worked.',
      '@user was the sane one. the delulu destroyer does not reward sanity.',
      '@user got eliminated erratically and the replay makes no sense.',
    ],
    revive: [
      '@user manifested their way back. the delusion continues.',
      '@user came back. the erratic energy carried them.',
      'the manic force pulled @user back into the arena.',
      '@user said I\'m not done and the universe agreed. somehow.',
    ],
    autoRevive: [
      '💚 the delulu energy revived @user. nobody planned this.',
      '💚 @user got back up. the chaos chose them. no reason.',
      '💚 erratic revival. @user is alive. the arena accepts this.',
    ],
  },

  // ── EAT DIRT ERA ───────────────────────────────────────────────────────────
  'eat dirt era': {
    name: 'Eat Dirt Era',
    color: '#a6fd29',
    intro: [
      'eat dirt era. the arena is not being metaphorical.',
      'dirt brown. dust beige. dark red. grounded. humiliating. correct.',
      'the most dominant energy the arena has hosted. eat dirt.',
      'eat dirt era activated. the ground is about to meet several faces.',
    ],
    fight: [
      '@attacker put @target face down in the dirt.',
      '@attacker said eat dirt to @target and enforced it.',
      '@attacker grounded @target immediately. no mercy.',
      '@target is on the floor. @attacker put them there.',
      '@attacker didn\'t just eliminate @target. @attacker made them eat dirt.',
      '@attacker dragged @target through the floor of the arena.',
      '@target went down hard. @attacker made sure of it.',
      '@attacker said floor check and @target passed.',
      '@attacker dominated @target and then stepped over them.',
      '@target hit the ground before they processed what happened.',
      '@attacker said stay down and @target did.',
      '@attacker put @target in the dirt and didn\'t look back.',
      '@target got grounded so hard the arena felt it.',
      '@attacker eliminated @target with the cruelty of someone who enjoys this.',
    ],
    win: [
      '@winner wins. everyone ate dirt. @winner provided it.',
      '@winner put every single player in the ground. champion.',
      '@winner wins. dominant. gritty. undefeated.',
      '@winner made the whole arena eat dirt and stood on top.',
      '@winner wins. dirt brown and dark red. the ground is @winner\'s.',
      '@winner said eat dirt to the arena. the arena complied.',
      '@winner is champion. the most humiliating victory for everyone else.',
      '@winner wins. everyone else is on the floor. @winner is not.',
    ],
    elim: [
      '@user ate dirt. the era delivered.',
      '@user is face down in the arena. eliminated.',
      '@user got grounded and not in the good way.',
      '@user hit the floor so fast the impact was audible.',
      '@user ate dirt and the arena said finish your plate.',
      '@user got put in the ground by someone who made it look effortless.',
      '@user is on the floor. the era is satisfied.',
      '@user got dominated so thoroughly the dirt felt strategic.',
    ],
    chaos: [
      { text: 'eat dirt era lived up to the name. someone hit the floor.',                   type: 'random_elim', count: 1 },
      { text: 'the dominant energy activated. multiple players grounded.',                   type: 'mass_elim',   count: 2 },
      { text: 'dirt chaos event. several players hit the floor simultaneously.',             type: 'mass_elim',   count: 3 },
      { text: 'the arena said eat dirt to someone. they complied.',                         type: 'random_elim', count: 1 },
      { text: 'gritty chaos. two players grounded without warning.',                         type: 'random_elim', count: 2 },
    ],
    humiliation: [
      '@user ate dirt and the arena asked if they wanted seconds.',
      '@user got put in the ground so hard the humiliation outlasted the pain.',
      '@user hit the floor with the energy of something that never stood a chance.',
      '@user got dominated by an era that named itself after their experience.',
      '@user ate dirt in front of everyone. the ground was better company.',
    ],
    revive: [
      '@user got back up from the dirt. covered in it. still back.',
      '@user stood up. the dirt didn\'t stop them.',
      '@user came back from the floor with something to prove.',
      '@user got up. the era is annoyed.',
    ],
    autoRevive: [
      '🟤 the arena pulled @user out of the dirt. they\'re back.',
      '🟤 @user refused to stay on the floor. revived.',
      '🟤 the ground gave @user back. eat dirt era is displeased.',
    ],
  },
};

// ── ERA NAME ALIASES ──────────────────────────────────────────────────────────
const ERA_ALIASES = {
  'gut':           'gut feeling era',
  'bite':          'darling i bite',
  'darling':       'darling i bite',
  'baddie':        'baddie body count',
  'body count':    'baddie body count',
  'kiss':          'kiss then kill',
  'eat':           'eat or be eaten',
  'buffet':        'blood buffet',
  'blood':         'blood buffet',
  'served':        'served you wrong',
  'wrong':         'served you wrong',
  'no survivors':  'no survivors era',
  'survivors':     'no survivors era',
  'you thought':   'you thought wrong',
  'delulu':        'delulu destroyer',
  'destroyer':     'delulu destroyer',
  'dirt':          'eat dirt era',
};

function resolveEra(input) {
  if (!input) return 'default';
  const lower = input.toLowerCase().trim();
  if (ERAS[lower]) return lower;
  if (ERA_ALIASES[lower]) return ERA_ALIASES[lower];
  // partial match
  for (const key of Object.keys(ERAS)) {
    if (key !== 'default' && key.includes(lower)) return key;
  }
  return null;
}

function getEra(name) {
  return ERAS[name] || ERAS['default'];
}

function listEras() {
  return Object.keys(ERAS).filter(k => k !== 'default');
}

module.exports = { ERAS, resolveEra, getEra, listEras };
